# -*- coding: utf-8 -*-
"""개선 필요 리뷰만 추출

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17OtRV-HtEobklo1fzOhnBm74xxl-pxuM
"""

import pandas as pd
import io
import csv

# 드라이브에 연결
from google.colab import drive
drive.mount('/content/drive')

city = pd.read_csv("/content/drive/Shareddrives/언어의미와정보 데이터캡스톤디자인/2021 리뷰 최종/city_spell_checked.csv")
hana = pd.read_csv("/content/drive/Shareddrives/언어의미와정보 데이터캡스톤디자인/2021 리뷰 최종/hana_spell_checked.csv")
k = pd.read_csv("/content/drive/Shareddrives/언어의미와정보 데이터캡스톤디자인/2021 리뷰 최종/k_spell_checked.csv")
kakao = pd.read_csv("/content/drive/Shareddrives/언어의미와정보 데이터캡스톤디자인/2021 리뷰 최종/kakao_spell_checked.csv")
kb = pd.read_csv("/content/drive/Shareddrives/언어의미와정보 데이터캡스톤디자인/2021 리뷰 최종/kb_spell_checked.csv")
nh = pd.read_csv("/content/drive/Shareddrives/언어의미와정보 데이터캡스톤디자인/2021 리뷰 최종/nh_spell_checked.csv")
sc = pd.read_csv("/content/drive/Shareddrives/언어의미와정보 데이터캡스톤디자인/2021 리뷰 최종/sc_spell_checked.csv")
sh = pd.read_csv("/content/drive/Shareddrives/언어의미와정보 데이터캡스톤디자인/2021 리뷰 최종/sh_spell_checked.csv")
shinhan = pd.read_csv("/content/drive/Shareddrives/언어의미와정보 데이터캡스톤디자인/2021 리뷰 최종/shinhan_spell_checked.csv")
toss = pd.read_csv("/content/drive/Shareddrives/언어의미와정보 데이터캡스톤디자인/2021 리뷰 최종/toss_spell_checked.csv")
woori = pd.read_csv("/content/drive/Shareddrives/언어의미와정보 데이터캡스톤디자인/2021 리뷰 최종/woori_spell_checked.csv")

bank = woori
bank_name = 'woori'

bank = bank.drop(columns=['Unnamed: 0', 'userName', 'date', 'thumbsUpCount'])
bank.head()
print(len(bank))

# 5점 리뷰 제거
bank = bank[(bank['score'] < 5)]
bank = bank.reset_index(drop=True)
print(len(bank))
bank.head()

# comment가 비어있는 경우와 10자 미만인 리뷰 제거
bank = bank.loc[[i for i in range(len(bank['comment'])) if (type(bank['comment'][i]) == str  and len(bank['comment'][i]) >= 10)]]

print(len(bank))
bank.head()

problems = bank.query('comment.str.contains("개선|부탁|필요|해주세|해주시면|해줘|해주셨으면|해주실|좋겠|좋을|나을")', engine='python')
print(len(problems))
problems.to_csv(bank_name+'_problems.csv')