# -*- coding: utf-8 -*-
"""중복 단어 제거 및 csv 병합.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JGoBD8Gb8cxGN82RGUq_v23kKY5Oe-H9
"""

import io
import csv
import os
import pandas as pd
import glob

dir_path = '/content/drive/Shareddrives/언어의미와정보 데이터캡스톤디자인/score_dic'
#files = glob.glob(dir_path + "*.csv")
all_score_dic= pd.DataFrame()

forder = glob.glob("/content/drive/Shareddrives/언어의미와정보 데이터캡스톤디자인/score_dic/*.csv")
total = pd.DataFrame()

for file_name in forder:
  temp = pd.read_csv(file_name, encoding='utf-8')
  total = pd.concat([total,temp])

total.to_csv('all_score_dic.csv')

total = pd.read_csv("/content/all_score_dic.csv")
total.head()

total = total.groupby(['WORD','TAG','reinforcer','score']).sum()
total.tail()

total.to_csv("total.csv")